# mapping to the lfl directories corresponding to each sample, in order of sample_0, sample_1, and so on
lfl_pbt_dirs = {
    'maze_115_trials': [
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_115_2ms/param_qO0EQo/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_115_2ms/param_SKimAm/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_115_2ms/param_BKiCrz/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_115_2ms/param_wUzJwa/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_115_2ms/param_-yQSln/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_115_2ms/param_hJXWSS/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_115_2ms/param_POmta_/d_003/pbt_run'],
    'maze_230_trials': [
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_230_2ms/param_etY12t/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_230_2ms/param_wcljOe/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_230_2ms/param_vg2Yk4/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_230_2ms/param_hCFAV4/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_230_2ms/param_KcHJrP/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_230_2ms/param_0D0E0o/d_003/pbt_run',
        '/snel/share/runs/PBT/Maze_fix/mazeJ3_trials_230_2ms/param_QVGDHr/d_003/pbt_run'],
    'chaotic_05_replications': [
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_0/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_1/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_2/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_3/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_4/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_5/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_6/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_7/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_8/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_05_replications/sample_9/pbt_run'],
    'chaotic_10_replications': [
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_0/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_1/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_2/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_3/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_4/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_5/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_6/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_7/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_8/pbt_run',
        '/snel/home/asedler/ray_results/pbt_validation_fullChaotic/chaotic/lfl/chaotic_10_replications/sample_9/pbt_run'],
}

# conversion dictionary from LF2 HP names to LFL HP names
convert_hps = {
    # 'MODEL.ALIGN_MODE': False,
    'MODEL.CD_PASS_RATE': 'cd_grad_passthru_prob',
    'MODEL.CD_RATE': 'keep_ratio',
    'MODEL.CI_ENC_DIM': 'ci_enc_dim',
    'MODEL.CON_DIM': 'con_dim',
    'MODEL.CO_DIM': 'co_dim',
    'MODEL.CO_PRIOR_NVAR': 'prior_ar_nvar',
    'MODEL.CO_PRIOR_TAU': 'prior_ar_atau',
    # 'MODEL.DATA_DIM': 100,
    'MODEL.DROPOUT_RATE': 'keep_prob',
    'MODEL.EXT_INPUT_DIM': 'ext_input_dim',
    'MODEL.FAC_DIM': 'factors_dim',
    'MODEL.GEN_DIM': 'gen_dim',
    'MODEL.IC_DIM': 'ic_dim',
    'MODEL.IC_ENC_DIM': 'ic_enc_dim',
    'MODEL.IC_POST_VAR_MIN': 'ic_post_var_min',
    'MODEL.IC_PRIOR_VAR': 'ic_prior_var',
    'MODEL.READIN_DIM': 'in_factors_dim',
    # 'MODEL.SEQ_LEN': 50,
    'MODEL.SV_SEED': 'cv_rand_seed',
    'MODEL.SV_RATE': 'cv_keep_ratio',
    'MODEL.CELL_CLIP': 'cell_clip_value',
    'MODEL.CI_LAG': 'controller_input_lag',
    'TRAIN.BATCH_SIZE': 'batch_size',
    'TRAIN.DATA.DIR': 'data_dir',
    'TRAIN.DATA.PREFIX': 'data_filename_stem',
    'TRAIN.KL.CO_WEIGHT': 'kl_co_weight',
    'TRAIN.KL.IC_WEIGHT': 'kl_ic_weight',
    'TRAIN.KL.INCREASE_EPOCH': 'kl_increase_epochs',
    'TRAIN.KL.START_EPOCH': 'kl_start_epoch',
    'TRAIN.L2.CI_ENC_SCALE': 'l2_ci_enc_scale',
    'TRAIN.L2.CON_SCALE': 'l2_con_scale',
    'TRAIN.L2.GEN_SCALE': 'l2_gen_scale',
    'TRAIN.L2.IC_ENC_SCALE': 'l2_ic_enc_scale',
    'TRAIN.L2.INCREASE_EPOCH': 'l2_increase_epochs',
    'TRAIN.L2.START_EPOCH': 'l2_start_epoch',
    'TRAIN.LOSS_SCALE': 'loss_scale',
    'TRAIN.LR.DECAY': 'learning_rate_decay_factor',
    'TRAIN.LR.INIT': 'learning_rate_init',
    'TRAIN.LR.PATIENCE': 'learning_rate_n_to_compare',
    'TRAIN.LR.STOP': 'learning_rate_stop',
    'TRAIN.ADAM_EPSILON': 'adam_epsilon',
    # 'TRAIN.MAX_EPOCHS': 'target_num_epochs', # missing from last year's lfadslite
    'TRAIN.MAX_GRAD_NORM': 'max_grad_norm',
    'TRAIN.MODEL_DIR': 'lfads_save_dir',
    # 'TRAIN.OVERWRITE': False,
    'TRAIN.PATIENCE': 'n_epochs_early_stop',
    # 'TRAIN.TUNE_MODE': False,
    # 'TRAIN.USE_TB': False,
}